# Site settings
title: Cindy's Blog/isomker's Blog/张迪的博客
email: uestc.zhangdi@gmail.com
description: 前端开发以及IOS开发相关博客.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://icindy.github.com" # the base hostname & protocol for your site
twitter_username: UestcZhang
github_username:  icindy
disqus_shortname: cindyfn

# Build settings
markdown: kramdown
# 开启分页
paginate: 5
